{% set name = "npth" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 8bd24b4f23a3065d6e5b26e98aba9ce783ea4fd781069c1b35d149694e90ca3e

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('npth') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  requires:
    - {{ compiler('c') }}
  source_files:
    - tests

about:
  home: https://www.gnupg.org/software/npth/index.html
  doc_url: https://www.gnupg.org/software/npth/index.html
  dev_url: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=npth.git
  summary: The New GNU Portable Threads Library
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING.LIB
  description: |
    nPth is a library to provide the GNU Pth API and thus a non-preemptive
    threads implementation.

    In contrast to GNU Pth is is based on the system's standard threads implementation.
    This allows the use of libraries which are not compatible to GNU Pth. Experience
    with a Windows Pth emulation showed that this is a solid way to provide a co-routine
    based framework.
extra:
  recipe-maintainers:
    - zklaus
    - mariusvniekerk
    - notestaff
