# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wPStbs6QF0wutHnqSzsIrv9XAatSkiKKhipOg77kK2/wFUNnJWJdVIeNV/9QIc5sxu1TmhEh/QKYy6h77tuwH7FTEGJKTxMHAXxY4HWl4fclGIfL/OhQSYh+wi2J4sA77MmZJZT9CepI4feFy+Awo6Da9AlvPF7mCj7imkAshDfnKn09dUa07+rmVjffSlhEHMKAhAt+z1pR+Ha4xPgJaXWsKxjx6Xakun78NeWkgE9eJEU5Eykd2+UNYjUE2BZN+LtJfgZLj9lgIEoeXYGNcH+hyF1lH0AFmpjRjkUqUUCjHkk5Bb+3CrWV4k4Vcx7ai03L7yfH5CUPyf0FL+LyVZWYiUth7uxWbybLzR7pNZ+3aGW6y3MyNRd8PSL34uEVdKJ6Q50dDg+dMmCTAtc/yMQmMX20y/RNcn1i5vii3XUetW0O4bNMRV3mlXE9he71+fXsYekhUdklsQOtUbDBqjhZ+OB1dac8bA/aNJCcMQ9Scc0beXzBN1fDqqu/0LPozCiw1kzYjBf8afHTDcCPF7ra+nMSoE0YJnz6IemwHySgnmoU+58ZS2BfpFW/FyjKKJMRQdc5Zy65+wbBGdzXu/EzmEhgBnRu8ja/Ffg1vyQ4F2ztj0GPn95gEp6pbm3B5Waihg+vI5iHJlP6cCGp8RuVMbCRu+hPeNmCHANzH18="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
