travis:
  secure:
    BINSTAR_TOKEN: kwlvLUqc9x+V10nsybog4rLQxDCC/AFmA/hox9JTg0voZkzUsWS3m8qHrmsikNamASz5EmT7Axy3YPveHR+NlTIYvxQUCwPB2eFwh68xdLZNpDlMdiNK59AChvjsg0xqgCO8ZqDo41YgNh9Gp1mDmC9v6dtqoHweprxhM37NhUG2YXur+jryIQ2378P8NnUoO327HVZ/eOn0F8XjmA+k6Y3XkZI2VRkNGMEA62SvNv6iceITr3BHKf/RGMOkhWS4rG0DwkrtEQRdUenoLsm8KWVO7+i6ZCX6XkGcP/ZzqvYp5u0U4sn/lwc6d1fPV10CIouEz1wtciTE4XFvoRMyG10VkRMyk5fGyd6L5Q+abyc1G8oD4we6rVHIqtWMA9ypOppXIBPx23ef3oY8S2oztm+lKN6P6kX/scYWitQDwfSANkxe3taMNmQXYwm0g+B9RTryWsBa4NGlyBN9BvXhHJUcHZNNI0tUTdxPbaF7OQCoiWtJNfe5rz1CjqWESDMi8xptiEveQNOA6ar4LcKHW36AdXBxJfh4+PFZ/RXvVEoJeQSiGEFoJsO4qkWpxchALIHYrIhk1rKI4HWP3DSSHrmTszKpuJoIaxSqB4gQfXbcFAOVg3Qgqi+TVkdTy0iJtA2NdhoaEZCiRASNl5jVtgdGUs83ur/TZElleUKlCfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
