appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wPStbs6QF0wutHnqSzsIrv9XAatSkiKKhipOg77kK2/wFUNnJWJdVIeNV/9QIc5sxu1TmhEh/QKYy6h77tuwH7FTEGJKTxMHAXxY4HWl4fclGIfL/OhQSYh+wi2J4sA77MmZJZT9CepI4feFy+Awo6Da9AlvPF7mCj7imkAshDfnKn09dUa07+rmVjffSlhEHMKAhAt+z1pR+Ha4xPgJaXWsKxjx6Xakun78NeWkgE9eJEU5Eykd2+UNYjUE2BZN+LtJfgZLj9lgIEoeXYGNcH+hyF1lH0AFmpjRjkUqUUCjHkk5Bb+3CrWV4k4Vcx7ai03L7yfH5CUPyf0FL+LyVZWYiUth7uxWbybLzR7pNZ+3aGW6y3MyNRd8PSL34uEVdKJ6Q50dDg+dMmCTAtc/yMQmMX20y/RNcn1i5vii3XUetW0O4bNMRV3mlXE9he71+fXsYekhUdklsQOtUbDBqjhZ+OB1dac8bA/aNJCcMQ9Scc0beXzBN1fDqqu/0LPozCiw1kzYjBf8afHTDcCPF7ra+nMSoE0YJnz6IemwHySgnmoU+58ZS2BfpFW/FyjKKJMRQdc5Zy65+wbBGdzXu/EzmEhgBnRu8ja/Ffg1vyQ4F2ztj0GPn95gEp6pbm3B5Waihg+vI5iHJlP6cCGp8RuVMbCRu+hPeNmCHANzH18=}
