travis:
  secure:
    BINSTAR_TOKEN: PtnUBjngVhi48/wsOj84qUVgdK09eCJC0GL3Nwt8PThBd82/MBbU9UIoKQnkTTlvLD+MMGxbFxvlp7i5PacKmvtXeyWqoLyGX0R3rQ7s2+a0GyFQeO7B51S2HpKHWxH4NyCj7gX3O9EPxfDLAEyFKhkhu4buQS8HyeiJDvE8iU1+mnExQaXRoqya8c4clFplVMe30PyGVENfGtJ6ciEVwvC8JGu1402daKs92gtv19vmttZRaVucdBuQRQZOvXcYRIOmMifubiJAmvjUfV4fiideJhc9gQALBLvGrtJOYusO0fFhZj91EbhqbN04mvbtpc17Es0r1sdpDUQH/dMRwWD5V+xRqQmhPtk03hLK3PWBCn7KQYYYotc6wdTTXKQ4Z0imUXplMEiVx6IpfKBi5Rvu1R5qbfk8F8qgUIT09J5CfeqIjgMoBhU7WibOLy0wrbWkRmvvbRrZJxQHe6qetrkvQQY7Y7BHoxlzIJiQTSgsRoYpiXvpz9dG5NGHp8oSEJu4JqkfXCj3D/ihKbKCA0UUA3xOWsWlBkP4PuPZf492bB28HKZnfUzC+NO22MYBzOQjMxv387+vQn+Y/CBbdJGfevM+JIsSaI6nE/8hdT58DyVzRiMFUOJyPr0uTYUINe6T/1VX8eSwMjDeKGxxa4NBJOJgkOITVImBvEUu1x8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
